---
- name: "Adding waf user to groups"
  user:
    name: "{{ WAF_USER }}"
    groups: gpio,spi,i2c,syslog,plugdev,dialout
    append: yes
  when: ENABLE_WAF
  tags: waf

- name: Install specified python requirements in indicated (virtualenv)
  ansible.builtin.pip:
    requirements: "{{WAF_PATH}}/requirements.txt"
    virtualenv: "{{WAF_PATH}}/.venv"
    virtualenv_python: python3
  # become: true
  # become_user: "{{ WAF_USER }}"
  # The env below was required in python 3.10, now with 3.12 I had to remove it
  # environment:
  #   SETUPTOOLS_USE_DISTUTILS: stdlib
  when: ENABLE_WAF
  tags:
    - waf

- name: "Create systemd and udev files"
  template:
    src: "templates/{{item}}.j2"
    dest: "/{{item}}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - etc/systemd/system/waf.service
    - etc/udev/rules.d/99-io.rules
# now using the rule from irmpd packet
#    - etc/udev/rules.d/70-irmp.rules
  when: ENABLE_WAF
  tags: waf

- name: "Create /etc/waf.yaml if not exists"
  template:
    src: "templates/{{item}}.j2"
    dest: "/{{item}}"
    owner: root
    group: root
    mode: "0644"
    force: false
  with_items:
    - etc/waf.yaml
  when: ENABLE_WAF
  tags: waf

- name: "Allow {{WAF_USER}} to run systemctl"
  community.general.sudoers:
    name: waf
    user: "{{WAF_USER}}"
    commands:
      - /bin/systemctl --no-block start vdr.service
    nopassword: true
  when: ENABLE_WAF and ENABLE_VDR
  tags: waf

- name: "Make sure waf is running"
  systemd:
    name: waf
    state: started
    enabled: yes 
    daemon_reload: yes
  when: ENABLE_WAF
  tags: waf
