---
- name: Install dependencies
  include_tasks:
    file: dependencies.yml
  when: ENABLE_WAF
  tags:
    - waf

- name: Prepare logs
  include_tasks:
    file: log.yml
  when: ENABLE_WAF
  tags:
    - waf

- name: Install waf daemon from git
  include_tasks:
    file: waf_install.yml
  when: ENABLE_WAF
  tags:
    - waf

- name: System integration
  include_tasks:
    file: integration.yml
  when: ENABLE_WAF
  tags:
    - waf
